# Generated by Django 5.0.1 on 2024-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_item_delete_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
